### ISSUE TITLE
Add a feedback tool

### ISSUE THREAD

**Issue by jlmdegoede** [jlmdegoede/MOOCworkbench#34]
We should gather feedback as early as possible.

**Comment by Donenzone** [comment]
It looks like this will need to be written manually, as no suitable solution seems to exist.

The feedback app should at least provide the following functionality:
- Show a form after specific actions performed in the workbench
- Consist of three forms: What did you like, What didn't you like, any other comments
- Ask if the experience of the user was positive or negative.

Also, look if some literature exists on how to effectively solicit feedback.

**Comment by Donenzone** [comment]
Started work on this.
Added Tasks, with a starting and end point, so as to give users know what they should test specifically. After a task is completed, the feedback form should automatically be presented.

**Comment by jlmdegoede** [comment]
The feedback tool is ready
